export const COLORS = {
  ink: "#0c0b14",
  night: "#14132a",
  dusk: "#232244",
  haze: "#3a3963",
  mist: "#5e5c8a",
  stoneDeep: "#1b1925",
  stoneDark: "#282535",
  stone: "#3a3649",
  stoneLight: "#544f66",
  stoneEdge: "#787290",
  metalDark: "#263040",
  metal: "#3f4c63",
  metalLight: "#7887a3",
  moon: "#f1ead2",
  moonShade: "#c4bb9c",
  ledOff: "#4d0f1a",
  led: "#e8283f",
  ledGlow: "#ff8f8f",
  keyword: "#569cd6",
  string: "#e05a61",
  comment: "#57a64a",
  function: "#ce67d3",
  cable: "#8fd0ff",
  skin: "#e9b38b",
  skinShade: "#b27a58",
  hair: "#2a1c18",
  white: "#f5f5f5",
  gold: "#f5c04a",
} as const;

export type Color = keyof typeof COLORS;

export const TRANSPARENT = ".";

export const PALETTE: Readonly<Record<string, Color>> = {
  k: "ink",
  n: "night",
  d: "dusk",
  h: "haze",
  m: "mist",
  "1": "stoneDeep",
  "2": "stoneDark",
  "3": "stone",
  "4": "stoneLight",
  "5": "stoneEdge",
  "6": "metalDark",
  "7": "metal",
  "8": "metalLight",
  o: "moon",
  q: "moonShade",
  r: "ledOff",
  R: "led",
  L: "ledGlow",
  b: "keyword",
  s: "string",
  g: "comment",
  v: "function",
  c: "cable",
  f: "skin",
  F: "skinShade",
  H: "hair",
  w: "white",
  y: "gold",
};
